[package]
name = "gpt-alarm"
version = "0.1.0"
edition = "2024"

[dependencies]
async-process = "2.5.0"
http = "1.4.0"
reqwest = "0.13.2"
serde_json = "1.0.149"
subprocess = "1.0.3"
tempdir = "0.3.7"
tokio = { version = "1.51.1", features = ["full"] }
nokhwa = { version = "0.10", features = ["input-native"] }
rodio = "0.20"
image = "0.25.10"
base64 = "0.22.1"
gstreamer = "0.25.2"
memchr = "2.8.0"
gpio = "0.4.1"
gpio-cdev = "0.6.0"
libc = "0.2.186"
gstreamer-app = {version="^0.25.2"}
chrono = "0.4.44"
